// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication7.Context;

#nullable disable

namespace WebApplication7.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20220831011742_SacarSeeds")]
    partial class SacarSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication7.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaID = 120,
                            Descripcion = "Lo que tengo que hacer",
                            Nombre = "Asuntos personales"
                        },
                        new
                        {
                            CategoriaID = 240,
                            Descripcion = "Lo que me obligan a hacer",
                            Nombre = "Asutos laborales"
                        });
                });

            modelBuilder.Entity("WebApplication7.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"), 1L, 1);

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<bool>("Procrastinable")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = 1450,
                            CategoriaID = 120,
                            Estado = false,
                            FechaCreacion = new DateTime(2022, 8, 30, 22, 17, 41, 872, DateTimeKind.Local).AddTicks(4473),
                            PrioridadTarea = 0,
                            Procrastinable = false,
                            Titulo = "Cebar mates"
                        },
                        new
                        {
                            TareaId = 2350,
                            CategoriaID = 240,
                            Estado = false,
                            FechaCreacion = new DateTime(2022, 8, 30, 22, 17, 41, 872, DateTimeKind.Local).AddTicks(4484),
                            PrioridadTarea = 0,
                            Procrastinable = false,
                            Titulo = "Terminar de prerpara la minimal API"
                        });
                });

            modelBuilder.Entity("WebApplication7.Models.Tarea", b =>
                {
                    b.HasOne("WebApplication7.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApplication7.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
